const express = require('express');
const os = require('node:os');
const path = require('node:path');
const { Pool } = require('pg');
const { buildSeed, CATEGORIES } = require('./seed');

const app = express();
const port = Number(process.env.PORT) || 3000;
const pool = process.env.DATABASE_URL
  ? new Pool({
      connectionString: process.env.DATABASE_URL,
      max: 5,
      connectionTimeoutMillis: 5000,
      idleTimeoutMillis: 30000,
    })
  : null;

const STATUSES = ['pending', 'preparing', 'shipped', 'delivered', 'cancelled'];
const LOW_STOCK = 10;
const DAY = 86_400_000;
const jstDate = new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Tokyo' });

let memory = null;

// ---------- data access (PostgreSQL or in-memory) ----------

async function insertRows(client, table, columns, rows) {
  const values = [];
  const tuples = rows.map((row) => {
    const slots = columns.map((column) => {
      values.push(row[column]);
      return `$${values.length}`;
    });
    return `(${slots.join(', ')})`;
  });
  await client.query(`INSERT INTO ${table} (${columns.join(', ')}) VALUES ${tuples.join(', ')}`, values);
}

// ponytail: resets on every process start, so autoscaled/restarted instances also wipe data.
// Gate on a DEPLOY_ID stored in the DB if that matters.
async function resetData() {
  const seed = buildSeed();
  if (!pool) {
    memory = seed;
    return;
  }

  const client = await pool.connect();
  try {
    await client.query('BEGIN');
    // serialize concurrent instance boots
    await client.query('SELECT pg_advisory_xact_lock(20261004)');
    await client.query('DROP TABLE IF EXISTS orders, products');
    await client.query(`
      CREATE TABLE products (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        sku TEXT GENERATED ALWAYS AS ('SKU-' || lpad(id::text, 4, '0')) STORED,
        name VARCHAR(80) NOT NULL,
        category VARCHAR(20) NOT NULL,
        price INT NOT NULL CHECK (price >= 0),
        stock INT NOT NULL CHECK (stock >= 0)
      )
    `);
    await client.query(`
      CREATE TABLE orders (
        id INT PRIMARY KEY,
        order_no VARCHAR(20) NOT NULL UNIQUE,
        customer VARCHAR(40) NOT NULL,
        prefecture VARCHAR(10) NOT NULL,
        product_id INT REFERENCES products(id) ON DELETE SET NULL,
        product_name VARCHAR(80) NOT NULL,
        quantity INT NOT NULL CHECK (quantity > 0),
        total INT NOT NULL CHECK (total >= 0),
        payment VARCHAR(20) NOT NULL,
        status VARCHAR(12) NOT NULL CHECK (status IN (${STATUSES.map((s) => `'${s}'`).join(', ')})),
        ordered_at TIMESTAMPTZ NOT NULL
      )
    `);
    await insertRows(client, 'products', ['id', 'name', 'category', 'price', 'stock'], seed.products);
    await client.query("SELECT setval(pg_get_serial_sequence('products', 'id'), (SELECT MAX(id) FROM products))");
    await insertRows(
      client,
      'orders',
      ['id', 'order_no', 'customer', 'prefecture', 'product_id', 'product_name', 'quantity', 'total', 'payment', 'status', 'ordered_at'],
      seed.orders,
    );
    await client.query('COMMIT');
  } catch (error) {
    await client.query('ROLLBACK');
    throw error;
  } finally {
    client.release();
  }
}

async function getProducts() {
  if (!pool) {
    return [...memory.products].sort((a, b) => b.id - a.id);
  }
  const { rows } = await pool.query('SELECT id, sku, name, category, price, stock FROM products ORDER BY id DESC');
  return rows;
}

async function getOrders() {
  if (!pool) {
    return [...memory.orders].reverse();
  }
  const { rows } = await pool.query(`
    SELECT id, order_no, customer, prefecture, product_id, product_name,
           quantity, total, payment, status, ordered_at
    FROM orders ORDER BY ordered_at DESC
  `);
  return rows;
}

async function updateOrderStatus(id, status) {
  if (!pool) {
    const order = memory.orders.find((item) => item.id === id);
    if (order) order.status = status;
    return Boolean(order);
  }
  const { rowCount } = await pool.query('UPDATE orders SET status = $1 WHERE id = $2', [status, id]);
  return rowCount > 0;
}

const skuFor = (id) => `SKU-${String(id).padStart(4, '0')}`;

async function createProduct({ name, category, price, stock }) {
  if (!pool) {
    const id = Math.max(0, ...memory.products.map((item) => item.id)) + 1;
    const product = { id, sku: skuFor(id), name, category, price, stock };
    memory.products.push(product);
    return product;
  }
  const { rows } = await pool.query(
    `INSERT INTO products (name, category, price, stock) VALUES ($1, $2, $3, $4)
     RETURNING id, sku, name, category, price, stock`,
    [name, category, price, stock],
  );
  return rows[0];
}

async function updateProduct(id, { name, category, price, stock }) {
  if (!pool) {
    const product = memory.products.find((item) => item.id === id);
    return product ? Object.assign(product, { name, category, price, stock }) : null;
  }
  const { rows } = await pool.query(
    `UPDATE products SET name = $1, category = $2, price = $3, stock = $4 WHERE id = $5
     RETURNING id, sku, name, category, price, stock`,
    [name, category, price, stock, id],
  );
  return rows[0] ?? null;
}

// orders keep product_name, so deleting a product never breaks order history
async function deleteProduct(id) {
  if (!pool) {
    const index = memory.products.findIndex((item) => item.id === id);
    if (index === -1) return false;
    memory.products.splice(index, 1);
    for (const order of memory.orders) if (order.product_id === id) order.product_id = null;
    return true;
  }
  const { rowCount } = await pool.query('DELETE FROM products WHERE id = $1', [id]);
  return rowCount > 0;
}

// ---------- dashboard ----------

// ponytail: aggregates in JS over all rows; move to SQL GROUP BY if orders grow past ~10k
function buildDashboard(orders, products, now = Date.now()) {
  const today = jstDate.format(now);
  const monthAgo = now - 30 * DAY;
  const valid = orders.filter((order) => order.status !== 'cancelled');
  const recent = valid.filter((order) => new Date(order.ordered_at).getTime() >= monthAgo);
  const monthSales = recent.reduce((sum, order) => sum + order.total, 0);

  const days = [];
  for (let offset = 13; offset >= 0; offset -= 1) {
    days.push({ date: jstDate.format(now - offset * DAY), sales: 0, orders: 0 });
  }
  const dayIndex = new Map(days.map((day) => [day.date, day]));
  for (const order of valid) {
    const day = dayIndex.get(jstDate.format(new Date(order.ordered_at)));
    if (day) {
      day.sales += order.total;
      day.orders += 1;
    }
  }

  const statusCounts = Object.fromEntries(STATUSES.map((status) => [status, 0]));
  for (const order of orders) statusCounts[order.status] += 1;

  const revenue = new Map();
  for (const order of recent) {
    const entry = revenue.get(order.product_name) ?? { name: order.product_name, sales: 0, units: 0 };
    entry.sales += order.total;
    entry.units += order.quantity;
    revenue.set(order.product_name, entry);
  }

  return {
    kpis: {
      todaySales: dayIndex.get(today).sales,
      todayOrders: dayIndex.get(today).orders,
      monthSales,
      monthOrders: recent.length,
      averageOrder: recent.length ? Math.round(monthSales / recent.length) : 0,
      toShip: statusCounts.pending + statusCounts.preparing,
    },
    daily: days,
    statusCounts,
    topProducts: [...revenue.values()].sort((a, b) => b.sales - a.sales).slice(0, 5),
    lowStock: products.filter((product) => product.stock < LOW_STOCK).sort((a, b) => a.stock - b.stock),
  };
}

// ---------- HTTP ----------

app.disable('x-powered-by');
app.use(express.json({ limit: '16kb' }));
app.use(express.static(path.join(__dirname, 'public')));

app.get('/api/dashboard', async (_req, res, next) => {
  try {
    const [orders, products] = await Promise.all([getOrders(), getProducts()]);
    res.json(buildDashboard(orders, products));
  } catch (error) {
    next(error);
  }
});

app.get('/api/orders', async (_req, res, next) => {
  try {
    res.json({ orders: await getOrders() });
  } catch (error) {
    next(error);
  }
});

app.patch('/api/orders/:id', async (req, res, next) => {
  const id = Number(req.params.id);
  const status = req.body?.status;
  if (!Number.isInteger(id) || !STATUSES.includes(status)) {
    return res.status(400).json({ error: 'invalid_status' });
  }
  try {
    return (await updateOrderStatus(id, status))
      ? res.json({ id, status })
      : res.status(404).json({ error: 'order_not_found' });
  } catch (error) {
    return next(error);
  }
});

function readProduct(body) {
  const name = typeof body?.name === 'string' ? body.name.trim() : '';
  const { category, price, stock } = body ?? {};
  const valid =
    name.length >= 1 &&
    name.length <= 80 &&
    CATEGORIES.includes(category) &&
    Number.isInteger(price) && price >= 0 && price <= 9_999_999 &&
    Number.isInteger(stock) && stock >= 0 && stock <= 99_999;
  return valid ? { name, category, price, stock } : null;
}

app.get('/api/products', async (_req, res, next) => {
  try {
    res.json({ products: await getProducts(), categories: CATEGORIES });
  } catch (error) {
    next(error);
  }
});

app.post('/api/products', async (req, res, next) => {
  const input = readProduct(req.body);
  if (!input) {
    return res.status(400).json({ error: 'invalid_product' });
  }
  try {
    return res.status(201).json({ product: await createProduct(input) });
  } catch (error) {
    return next(error);
  }
});

app.put('/api/products/:id', async (req, res, next) => {
  const id = Number(req.params.id);
  const input = readProduct(req.body);
  if (!Number.isInteger(id) || !input) {
    return res.status(400).json({ error: 'invalid_product' });
  }
  try {
    const product = await updateProduct(id, input);
    return product ? res.json({ product }) : res.status(404).json({ error: 'product_not_found' });
  } catch (error) {
    return next(error);
  }
});

app.delete('/api/products/:id', async (req, res, next) => {
  const id = Number(req.params.id);
  if (!Number.isInteger(id)) {
    return res.status(400).json({ error: 'bad_request' });
  }
  try {
    return (await deleteProduct(id)) ? res.status(204).end() : res.status(404).json({ error: 'product_not_found' });
  } catch (error) {
    return next(error);
  }
});

app.get('/health', async (_req, res) => {
  let database = 'memory';
  if (pool) {
    try {
      await pool.query('SELECT 1');
      database = 'connected';
    } catch (error) {
      console.error('DB check failed:', error.code || error.name);
      database = 'unavailable';
    }
  }
  res.status(database === 'unavailable' ? 503 : 200).json({
    status: database === 'unavailable' ? 'degraded' : 'ok',
    database,
    host: os.hostname(),
    uptimeSeconds: Math.floor(process.uptime()),
  });
});

app.use((error, _req, res, _next) => {
  console.error('Request failed:', error.code || error.type || error.name);
  res.status(error.status || 500).json({ error: error.status ? 'bad_request' : 'server_error' });
});

resetData()
  .then(() => {
    app.listen(port, () => {
      console.log(`Iris Commerce Admin on port ${port} (${pool ? 'PostgreSQL' : 'in-memory'}, data reset)`);
    });
  })
  .catch((error) => {
    console.error('Startup reset failed:', error.code || error.message);
    process.exit(1);
  });
